[[services]]
name = "web"

[services.build]
builder = "nixpacks"

[services.deploy]
startCommand = "daphne -b 0.0.0.0 -p $PORT typing_master.asgi:application"
healthcheckPath = "/health/"
restartPolicyType = "on_failure"

[[services]]
name = "worker"

[services.build]
builder = "nixpacks"

[services.deploy]
startCommand = "python manage.py runworker"
restartPolicyType = "on_failure"
