# Generated by Django 5.0.6 on 2026-05-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userstreak_xptransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avg_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avg_wpm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
